### ISSUE TITLE
Name [java:comp/env] is not bound in this Context. Unable to find [java:comp]

### ISSUE THREAD

**Issue by danieldavidraj** [heroku/webapp-runner#251]
This is my webapp/META-INF/context.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<Context>
    <Resource 
        name="jdbc/Postgres"
        auth="Container"
        type="javax.sql.DataSource"
        username="sgwmhdowrpujsg"
        password="3df7d192aa6ee4d0497aa1291c23270d6eeb8455558f23dbb88ec0ab70892ac6"
        driverClassName="org.postgresql.Driver"
        url="jdbc:postgresql://ec2-184-73-25-2.compute-1.amazonaws.com:5432/duo2buh5bsqqq?sslmode=require"
        maxTotal="25"
        maxIdle="10"
        validationQuery="select 1"
    />
</Context>
```
This is webapp/WEB-INF/web.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE web-app PUBLIC
 "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
 "http://java.sun.com/dtd/web-app_2_3.dtd" >

<web-app>
  <resource-ref>
    <description>Postgres Database</description>
    <res-ref-name>jdbc/Postgres</res-ref-name>
    <res-type>javax.sql.DataSource</res-type>
    <res-auth>Container</res-auth>
  </resource-ref>
</web-app>
```
java/user1.java -> I am getting error at line 46
```
import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import javax.servlet.annotation.WebServlet;

@WebServlet("/user1")
public class user1 extends HttpServlet {
	Connection con;
	Statement st;
	PrintWriter out;
	ResultSet rs;
	boolean b=false;

	public void init(ServletConfig sc)throws ServletException {
		try {
			System.setProperty(Context.INITIAL_CONTEXT_FACTORY, "org.apache.naming.java.javaURLContextFactory");
			
			super.init(sc);

			Context initCtx = new InitialContext();
			Context envCtx = (Context) initCtx.lookup("java:comp/env");
			DataSource ds = (DataSource) envCtx.lookup("jdbc/Postgres");
			
			con = ds.getConnection();
			st=con.createStatement();
		} catch(Exception e) {
			System.out.println(e.toString());
		}
	}
	public void service(HttpServletRequest req,HttpServletResponse res) throws ServletException,IOException { 
		try {


	 		res.setContentType("text/html");
			out=res.getWriter();

			String u=req.getParameter("una");
			String p=req.getParameter("pwd");

			String sql = "CREATE TABLE IF NOT EXISTS mailusers ("
	                + "	uname varchar(255) NOT NULL,"
	                + "	pwd varchar(255) NOT NULL)";
            st.execute(sql); 

			out.println("<html><body>");

			rs=st.executeQuery("select pwd from mailusers where uname='"+u+"'"); 
			if(rs.next()) {
				String pwd=rs.getString(1);
				if(pwd.equals(p)) {
					Cookie cook=new Cookie("signin",u);
					res.addCookie(cook);
					out.println("<script type=\"text/javascript\">");
					out.println("alert('Correct username');");
					out.println("location='inbox.html';");
					out.println("</script>");
				}
				else {
					out.println("<script type=\"text/javascript\">");
					out.println("alert('Type correct password');");
					out.println("location='index.html';");
					out.println("</script>");
				}
			}
			else {
				out.println("<script type=\"text/javascript\">");
				out.println("alert('Invalid user Name');");
				out.println("location='index.html';");
				out.println("</script>");
			}

			out.println("</body></html>");
		} catch(Exception e) {
			out.println(e.toString());
			e.printStackTrace();
		}
	}
}
```
This is the error
```
javax.naming.NameNotFoundException: Name [java:comp/env] is not bound in this Context. Unable to find [java:comp].
java.lang.NullPointerException: Cannot invoke "java.sql.Statement.execute(String)" because "this.st" is null
        at user1.service(user1.java:46)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
This is completely working fine in Tomcat 9.0.56 but getting this error in webapp runner using the command
```
java -jar target/dependency/webapp-runner.jar target/*.war
```

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)

**Comment by TilmeezUrRehmanBhatti** [comment]
how did you solvéthis error
