### ISSUE TITLE
Not working @Interceptor CDI / Weld

### ISSUE THREAD

**Issue by rodrigoguedes** [heroku/webapp-runner#37]
I'm having problems when using CDI 

At start App:

```
Fev 24, 2014 2:07:07 PM org.apache.catalina.core.StandardContext listenerStart
Grave: Exception sending context initialized event to listener instance of class org.jboss.weld.environment.servlet.Listener
org.jboss.weld.exceptions.DeploymentException: WELD-001417: Enabled interceptor class <class>br.com.guedesdesouza.infra.persistencia.transacao.TransacionalInterceptor</class> in jndi:/localhost/WEB-INF/beans.xml@7 is neither annotated @Interceptor nor registered through a portable extension
    at org.jboss.weld.bootstrap.Validator.validateEnabledInterceptorClasses(Validator.java:647)
    at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:470)
    at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:425)
```

If run Tomcat (physical Installation) the problem does not occur

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
