### ISSUE TITLE
Incorrectly appends default memcached port to provided port, thus breaking all memcached backed session functionality

### ISSUE THREAD

**Issue by edwardotis** [heroku/webapp-runner#60]
On Tomcat 8.0.30, oracle jdk 8.77
Using https://github.com/jsimone/webapp-runner with server string for MEMCACHE_SERVERS:
 n1:pub-memcache-42.us-east-1-1.1.ec2.garantiadata.com:11733

Results in default port being appended to provided port:
a
Apr 13, 2016 4:52:57 AM de.javakaffee.web.msm.MemcachedSessionService startInternal
INFO:  starts initialization... (configured nodes definition n1:pub-memcache-42.us-east-1-1.1.ec2.garantiadata.com:11733:11211, failover nodes null)
Apr 13, 2016 4:52:57 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5272)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Configured memcachedNodes attribute has wrong format, must match ([\w]+):([^:]+):([\d]+)(?:(?:\s+|,)([\w]+):([^:]+):([\d]+))*
    at de.javakaffee.web.msm.MemcachedNodesManager.createFor(MemcachedNodesManager.java:190)
    at de.javakaffee.web.msm.MemcachedSessionService.createMemcachedNodesManager(MemcachedSessionService.java:480)
    at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:423)
    at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:518)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 8 more

Reference
https://github.com/magro/memcached-session-manager/issues/294

**Comment by edwardotis** [comment]
Here's the line that is incorrectly adding default port, and thus breaking all possible providers of memcached on heroku, except for the custom supported memcachier. 

manager.setMemcachedNodes(System.getenv("MEMCACHE_SERVERS") + ":11211");

https://github.com/jsimone/webapp-runner/blob/df41b59e1bb36755ed614809b6ad6a235465100a/src/main/java/webapp/runner/launch/MemcacheSessionStore.java#L25

In fact, all the code around parsing MEMCACHE_SERVERS is broken. It fails to support multiple memcached servers, and thus breaks the contract with the underlying memached session library.

**Comment by jkutner** [comment]
I will gladly accept a PR for that. Looks like it should probably work like the `MEMCACHIER_SERVERS` env var.

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
